[project]
name = "seasoning-agriculture-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "pandas>=3.0.5",
    "pd>=0.0.4",
    "seaborn>=0.13.2",
    "sns>=0.1",
]

[project.scripts]
seasoning-agriculture-analysis = "seasoning_agriculture_analysis:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
